# Generated by Django 4.2.1 on 2023-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_produccion_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='produccion_cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
