# Generated by Django 4.2.1 on 2023-07-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_produccion_produccion_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='productos',
            new_name='materias',
        ),
    ]
