# Generated by Django 4.2.1 on 2023-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_rename_productos_produccion_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
