# Generated by Django 4.2.1 on 2023-07-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias_primas', '0002_productos_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='img',
            new_name='imagen',
        ),
    ]
