# Generated by Django 4.2.1 on 2023-07-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_primas', '0003_rename_img_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
