# Generated by Django 4.2.1 on 2023-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_proveedores_produccion'),
        ('materias_primas', '0003_remove_materias_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='proveedores',
            field=models.ManyToManyField(to='proveedores.proveedores'),
        ),
    ]
