# Generated by Django 4.2.1 on 2023-08-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_proveedores_produccion'),
        ('materias_primas', '0004_materias_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='materias',
            name='proveedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
        ),
    ]
