# Generated by Django 4.2.1 on 2023-08-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0006_produccion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envasado', to='produccion.produccion')),
            ],
            options={
                'verbose_name': 'envasado',
                'db_table': 'envasado',
            },
        ),
    ]
