# Generated by Django 4.2.1 on 2023-08-01 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0005_rename_productos_produccion_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='produccion.produccion')),
            ],
        ),
    ]
