# Generated by Django 4.2.1 on 2023-08-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedores'},
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
    ]
