# Generated by Django 4.2.1 on 2023-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedores_options_alter_proveedores_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
