# Generated by Django 4.2.1 on 2023-08-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedores_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='tel',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
