# Generated by Django 4.2.1 on 2023-08-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_remove_proveedores_tel_proveedores_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='produccion',
        ),
    ]
