# Generated by Django 4.2.1 on 2023-08-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_proveedores_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='apellido',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
