# Generated by Django 4.2.1 on 2023-09-11 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0007_alter_produccion_materias'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('costo', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion')),
            ],
        ),
    ]
