# Generated by Django 4.2.1 on 2023-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
