# Generated by Django 4.2.1 on 2023-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('imagen', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
